name: Test 02 Perms
on:
  push:
    branches: [test/gha-binsearch-1]
jobs:
  test:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
